In [1]:
import pandas as pd

# Read the data from the TSV file
pathDf = pd.read_csv('../data/Wikispeedia/paths_finished2.tsv', sep='\t')

pathDf

,hashedIpAddress,timestamp,durationInSec,path,rating
0,6a3701d319fc3754,1297740409,166,14th_century;15th_century;16th_century;Pacific...,NaN
1,3824310e536af032,1344753412,88,14th_century;Europe;Africa;Atlantic_slave_trad...,3.0
2,415612e93584d30e,1349298640,138,14th_century;Niger;Nigeria;British_Empire;Slav...,NaN
3,64dd5cd342e3780c,1265613925,37,14th_century;Renaissance;Ancient_Greece;Greece,NaN
4,015245d773376aab,1366730828,175,14th_century;Italy;Roman_Catholic_Church;HIV;R...,3.0
...,...,...,...,...,...
51313,15a13a1d66ef5456,1349231015,66,Yagan;Ancient_Egypt;Civilization,NaN
51314,2ef7ac844cefda58,1300254138,165,Yagan;Folklore;Brothers_Grimm;<;19th_century;C...,3.0
51315,12863abb7887f890,1385095372,228,Yagan;Australia;England;France;United_States;T...,NaN
51316,19f8284371753362,1298792567,56,Yarralumla%2C_Australian_Capital_Territory;Aus...,1.0
51317,24b84602179de377,1318122701,30,Ziad_Jarrah;Germany;Jew,NaN

In [2]:
# Define a function to process each path
def process_path(path):
    splittedPath = path.split(';')
    history = []
    result = []
    for page in splittedPath:
        if page != '<':
            # Move forward: add the page to history and result
            history.append(page)
            result.append(page)
        else:
            # Move back: remove the last page from history if possible
            if history:
                history.pop()
            # After moving back, get the current page
            if history:
                current_page = history[-1]
            else:
                current_page = ''  # Handle empty history as needed
            result.append(current_page)
    return ';'.join(result)

In [3]:
pathDf['path'] = pathDf['path'].apply(process_path)
pathDf

,hashedIpAddress,timestamp,durationInSec,path,rating
0,6a3701d319fc3754,1297740409,166,14th_century;15th_century;16th_century;Pacific...,NaN
1,3824310e536af032,1344753412,88,14th_century;Europe;Africa;Atlantic_slave_trad...,3.0
2,415612e93584d30e,1349298640,138,14th_century;Niger;Nigeria;British_Empire;Slav...,NaN
3,64dd5cd342e3780c,1265613925,37,14th_century;Renaissance;Ancient_Greece;Greece,NaN
4,015245d773376aab,1366730828,175,14th_century;Italy;Roman_Catholic_Church;HIV;R...,3.0
...,...,...,...,...,...
51313,15a13a1d66ef5456,1349231015,66,Yagan;Ancient_Egypt;Civilization,NaN
51314,2ef7ac844cefda58,1300254138,165,Yagan;Folklore;Brothers_Grimm;Folklore;19th_ce...,3.0
51315,12863abb7887f890,1385095372,228,Yagan;Australia;England;France;United_States;T...,NaN
51316,19f8284371753362,1298792567,56,Yarralumla%2C_Australian_Capital_Territory;Aus...,1.0
51317,24b84602179de377,1318122701,30,Ziad_Jarrah;Germany;Jew,NaN

In [4]:
pathDf.to_csv('../data/paths_no_back_links.tsv', sep='\t', index=False)